# Docker Compose override for testing failures
# Usage: docker-compose -f docker-compose.yml -f docker-compose.failures.yml up

services:
  validator:
    environment:
      - NODE_ENV=development
      - VALIDATOR_FAIL=1  # Force validator to fail

  queue:
    environment:
      - NODE_ENV=development
      - QUEUE_FAIL=1      # Force queue to fail

  pipeline-monitor:
    environment:
      - NODE_ENV=development
      - VALIDATOR_URL=http://validator:3001/health
      - QUEUE_HEALTH_URL=http://queue:3002/health
      - VALIDATOR_WARM_URL=http://validator:3001/warm
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:pipeline-alerts
      - PIPELINE_NAME=ess-publishing-local
      - PORT=8080
      - HEALTH_INTERVAL_MS=10000
      - AWS_REGION=us-east-1
      - STATUS_TABLE=PipelineStatus
      - AUDIT_TABLE=PipelineAudit
      - BREAKER_TIMEOUT=5000
      - ERROR_THRESHOLD=50
      - VOLUME_THRESHOLD=5
      - RESET_TIMEOUT=15000
      - AUDIT_TTL_DAYS=7
      - DBWRITE_FAIL=1    # Force DB write health check to fail
